const result = n => {
  let fibo = 0,
    n1 = 1,
    n2 = 2;

  while (n1 <= n) {
    if (n1 % 2 === 0) {
      fibo += n1;
    }

    // ? swap
    [n1, n2] = [n2, n1 + n2];
  }

  return fibo;
};

console.log(result(4000000));

/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/
